///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test_Case.Recordings.Helper
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SignIn recording.
    /// </summary>
    [TestModule("d3885c5c-3be0-4430-9b60-bf1bd6d0e433", ModuleType.Recording, 1)]
    public partial class SignIn : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Test_Case.Test_CaseRepository repository.
        /// </summary>
        public static global::Test_Case.Test_CaseRepository repo = global::Test_Case.Test_CaseRepository.Instance;

        static SignIn instance = new SignIn();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SignIn()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SignIn Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.PageWrapper.HeaderUyeGirisi' at 50;16.", repo.TestCaseStudy.PageWrapper.HeaderUyeGirisiInfo, new RecordItemIndex(0));
            repo.TestCaseStudy.PageWrapper.HeaderUyeGirisi.Click("50;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.CustomerEmail' at 99;21.", repo.TestCaseStudy.CustomerEmailInfo, new RecordItemIndex(1));
            repo.TestCaseStudy.CustomerEmail.Click("99;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'seleniumtester102@gmail.com' with focus on 'TestCaseStudy.CustomerEmail'.", repo.TestCaseStudy.CustomerEmailInfo, new RecordItemIndex(2));
            repo.TestCaseStudy.CustomerEmail.PressKeys("seleniumtester102@gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.CustomerPassword' at 64;26.", repo.TestCaseStudy.CustomerPasswordInfo, new RecordItemIndex(3));
            repo.TestCaseStudy.CustomerPassword.Click("64;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Test102!' with focus on 'TestCaseStudy.CustomerPassword'.", repo.TestCaseStudy.CustomerPasswordInfo, new RecordItemIndex(4));
            repo.TestCaseStudy.CustomerPassword.PressKeys("Test102!");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.ButtonTagGiriş' at 232;29.", repo.TestCaseStudy.ButtonTagGirişInfo, new RecordItemIndex(5));
            repo.TestCaseStudy.ButtonTagGiriş.Click("232;29");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='test test') on item 'TestCaseStudy.PageWrapper.TestTest'.", repo.TestCaseStudy.PageWrapper.TestTestInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.TestCaseStudy.PageWrapper.TestTestInfo, "InnerText", "test test");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
