///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test_Case.Recordings.CaseHash5
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddMultipleProductsToFav recording.
    /// </summary>
    [TestModule("db6cd160-2212-48d4-9352-85d6a106ac16", ModuleType.Recording, 1)]
    public partial class AddMultipleProductsToFav : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Test_Case.Test_CaseRepository repository.
        /// </summary>
        public static global::Test_Case.Test_CaseRepository repo = global::Test_Case.Test_CaseRepository.Instance;

        static AddMultipleProductsToFav instance = new AddMultipleProductsToFav();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddMultipleProductsToFav()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddMultipleProductsToFav Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.BtnEGift' at 32;22.", repo.TestCaseStudy.BtnEGiftInfo, new RecordItemIndex(0));
            repo.TestCaseStudy.BtnEGift.Click("32;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'TestCaseStudy.ProductList.Product1' at 224;380.", repo.TestCaseStudy.ProductList.Product1Info, new RecordItemIndex(1));
            repo.TestCaseStudy.ProductList.Product1.MoveTo("224;380");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'TestCaseStudy.ProductList.Product1' at 224;380.", repo.TestCaseStudy.ProductList.Product1Info, new RecordItemIndex(2));
            repo.TestCaseStudy.ProductList.Product1.MoveTo("224;380");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.ProductList.BtnAddFav1' at 15;10.", repo.TestCaseStudy.ProductList.BtnAddFav1Info, new RecordItemIndex(3));
            repo.TestCaseStudy.ProductList.BtnAddFav1.Click("15;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'TestCaseStudy.ProductList.Product2' at 276;404.", repo.TestCaseStudy.ProductList.Product2Info, new RecordItemIndex(4));
            repo.TestCaseStudy.ProductList.Product2.MoveTo("276;404");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.ProductList.BtnAddFav2' at 12;10.", repo.TestCaseStudy.ProductList.BtnAddFav2Info, new RecordItemIndex(5));
            repo.TestCaseStudy.ProductList.BtnAddFav2.Click("12;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.PageWrapper.BtnUser' at 48;36.", repo.TestCaseStudy.PageWrapper.BtnUserInfo, new RecordItemIndex(6));
            repo.TestCaseStudy.PageWrapper.BtnUser.Click("48;36");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.PageWrapper.BtnFavorites' at 103;19.", repo.TestCaseStudy.PageWrapper.BtnFavoritesInfo, new RecordItemIndex(7));
            repo.TestCaseStudy.PageWrapper.BtnFavorites.Click("103;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\n            Dijital Gift Card 250 TL\n        ') on item 'TestCaseStudy.PageWrapper.SpanTagDijitalGiftCard25'.", repo.TestCaseStudy.PageWrapper.SpanTagDijitalGiftCard25Info, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.TestCaseStudy.PageWrapper.SpanTagDijitalGiftCard25Info, "InnerText", "\n            Dijital Gift Card 250 TL\n        ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\n            Dijital Gift Card 500 TL\n        ') on item 'TestCaseStudy.PageWrapper.SpanTagDijitalGiftCard50'.", repo.TestCaseStudy.PageWrapper.SpanTagDijitalGiftCard50Info, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.TestCaseStudy.PageWrapper.SpanTagDijitalGiftCard50Info, "InnerText", "\n            Dijital Gift Card 500 TL\n        ");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
