///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test_Case.Recordings.CaseHash7
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SignOut recording.
    /// </summary>
    [TestModule("b090813b-9385-471a-b12f-09615dde76e3", ModuleType.Recording, 1)]
    public partial class SignOut : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Test_Case.Test_CaseRepository repository.
        /// </summary>
        public static global::Test_Case.Test_CaseRepository repo = global::Test_Case.Test_CaseRepository.Instance;

        static SignOut instance = new SignOut();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SignOut()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SignOut Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.PageWrapper.BtnUser' at 74;29.", repo.TestCaseStudy.PageWrapper.BtnUserInfo, new RecordItemIndex(0));
            repo.TestCaseStudy.PageWrapper.BtnUser.Click("74;29");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.PageWrapper.BtnSignOut' at 76;29.", repo.TestCaseStudy.PageWrapper.BtnSignOutInfo, new RecordItemIndex(1));
            repo.TestCaseStudy.PageWrapper.BtnSignOut.Click("76;29");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Üye Ol') on item 'TestCaseStudy.HeaderUyeOl'.", repo.TestCaseStudy.HeaderUyeOlInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.TestCaseStudy.HeaderUyeOlInfo, "InnerText", "Üye Ol");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Üye Girişi') on item 'TestCaseStudy.PageWrapper.HeaderUyeGirisi'.", repo.TestCaseStudy.PageWrapper.HeaderUyeGirisiInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.TestCaseStudy.PageWrapper.HeaderUyeGirisiInfo, "InnerText", "Üye Girişi");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
