///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Test_Case
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Test_CaseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ec37a76f-32b2-497b-8482-412e44fe3c32")]
    public partial class Test_CaseRepository : RepoGenBaseFolder
    {
        static Test_CaseRepository instance = new Test_CaseRepository();
        Test_CaseRepositoryFolders.TestCaseStudyAppFolder _testcasestudy;

        /// <summary>
        /// Gets the singleton class instance representing the Test_CaseRepository element repository.
        /// </summary>
        [RepositoryFolder("ec37a76f-32b2-497b-8482-412e44fe3c32")]
        public static Test_CaseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Test_CaseRepository() 
            : base("Test_CaseRepository", "/", null, 0, false, "ec37a76f-32b2-497b-8482-412e44fe3c32", ".\\RepositoryImages\\Test_CaseRepositoryec37a76f.rximgres")
        {
            _testcasestudy = new Test_CaseRepositoryFolders.TestCaseStudyAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ec37a76f-32b2-497b-8482-412e44fe3c32")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The TestCaseStudy folder.
        /// </summary>
        [RepositoryFolder("b3b7adfd-dc33-4b56-a07f-dd4cb5549ff1")]
        public virtual Test_CaseRepositoryFolders.TestCaseStudyAppFolder TestCaseStudy
        {
            get { return _testcasestudy; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Test_CaseRepositoryFolders
    {
        /// <summary>
        /// The TestCaseStudyAppFolder folder.
        /// </summary>
        [RepositoryFolder("b3b7adfd-dc33-4b56-a07f-dd4cb5549ff1")]
        public partial class TestCaseStudyAppFolder : RepoGenBaseFolder
        {
            Test_CaseRepositoryFolders.RegisterFormFolder _registerform;
            Test_CaseRepositoryFolders.ProductListFolder _productlist;
            Test_CaseRepositoryFolders.PageWrapperFolder _pagewrapper;
            Test_CaseRepositoryFolders.DivTagRowFolder _divtagrow;
            RepoItemInfo _headercontainerboynerInfo;
            RepoItemInfo _btnsigninInfo;
            RepoItemInfo _btnregisterInfo;
            RepoItemInfo _headeruyeolInfo;
            RepoItemInfo _fieldnameInfo;
            RepoItemInfo _fieldsurnameInfo;
            RepoItemInfo _fieldemailInfo;
            RepoItemInfo _fieldpasswordInfo;
            RepoItemInfo _fieldpasswordconfirmedInfo;
            RepoItemInfo _fieldphoneInfo;
            RepoItemInfo _btnfeedbackInfo;
            RepoItemInfo _errorfornameInfo;
            RepoItemInfo _errorforsurnameInfo;
            RepoItemInfo _errorforemailInfo;
            RepoItemInfo _errorforpasswordInfo;
            RepoItemInfo _errorforpasswordconfirmedInfo;
            RepoItemInfo _errorforphoneInfo;
            RepoItemInfo _errorformembershipagreementInfo;
            RepoItemInfo _btnquicklk1Info;
            RepoItemInfo _btnaddbasket1Info;
            RepoItemInfo _btnquicklk2Info;
            RepoItemInfo _h1tagbasketcountInfo;
            RepoItemInfo _btnbasketpageInfo;
            RepoItemInfo _basketitem1Info;
            RepoItemInfo _basketitem2Info;
            RepoItemInfo _buttontaggirişInfo;
            RepoItemInfo _customerpasswordInfo;
            RepoItemInfo _customeremailInfo;
            RepoItemInfo _btnegiftInfo;
            RepoItemInfo _btnaddbasket2Info;
            RepoItemInfo _ostepitemInfo;
            RepoItemInfo _ostepitem1Info;
            RepoItemInfo _deliveryInfo;

            /// <summary>
            /// Creates a new TestCaseStudy  folder.
            /// </summary>
            public TestCaseStudyAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TestCaseStudy", "/dom[@domain='www.boyner.com.tr']", parentFolder, 30000, null, false, "b3b7adfd-dc33-4b56-a07f-dd4cb5549ff1", "")
            {
                _registerform = new Test_CaseRepositoryFolders.RegisterFormFolder(this);
                _productlist = new Test_CaseRepositoryFolders.ProductListFolder(this);
                _pagewrapper = new Test_CaseRepositoryFolders.PageWrapperFolder(this);
                _divtagrow = new Test_CaseRepositoryFolders.DivTagRowFolder(this);
                _headercontainerboynerInfo = new RepoItemInfo(this, "HeaderContainerBoyner", "?/?/header/div", "?/?/header/div", 30000, null, "72f3aad7-51af-4aa6-8357-9f0884410e17");
                _btnsigninInfo = new RepoItemInfo(this, "BtnSignIn", "body/div[1]//nav/button[1]", ".//nav/button[1]", 30000, null, "a4613861-584d-4c54-bdf5-7f48629c6e10");
                _btnregisterInfo = new RepoItemInfo(this, "BtnRegister", "body/div[1]//nav/button[2]", ".//nav/button[2]", 30000, null, "7aa81104-95d8-4900-8f31-ba567f11d4cb");
                _headeruyeolInfo = new RepoItemInfo(this, "HeaderUyeOl", ".//body[#'mainBody']/div[1]/header/div[2]/div[1]/div[2]/div/div[3]/ul/?/?/ul//span[@innertext='Üye Ol']", ".//body[#'mainBody']//span[@innertext='Üye Ol']", 30000, null, "a3cedfab-5eed-460b-b9d9-f05500f5e937");
                _fieldnameInfo = new RepoItemInfo(this, "FieldName", ".//input[#'name']", ".//input[#'name']", 30000, null, "e41ac9c3-3d07-4623-baee-d964dd083914");
                _fieldsurnameInfo = new RepoItemInfo(this, "FieldSurname", ".//input[#'surname']", ".//input[#'surname']", 30000, null, "9cda977a-8125-4bca-b7cf-02f1fd3cf319");
                _fieldemailInfo = new RepoItemInfo(this, "FieldEmail", ".//input[#'email']", ".//input[#'email']", 30000, null, "6d18d7b5-1efc-4cdb-87c3-de11c44621a6");
                _fieldpasswordInfo = new RepoItemInfo(this, "FieldPassword", ".//input[#'password']", ".//input[#'password']", 30000, null, "3e4e9a1b-6502-42d8-a8fe-f36571d65ce5");
                _fieldpasswordconfirmedInfo = new RepoItemInfo(this, "FieldPasswordConfirmed", ".//input[#'passwordConfirmed']", ".//input[#'passwordConfirmed']", 30000, null, "4059b3b9-eb82-4269-9cfc-21b4f4936325");
                _fieldphoneInfo = new RepoItemInfo(this, "FieldPhone", ".//input[#'phone']", ".//input[#'phone']", 30000, null, "67c71b35-1e5b-4ab8-accd-0b5f127ac1e9");
                _btnfeedbackInfo = new RepoItemInfo(this, "BtnFeedback", ".//div[#'_hj_feedback_container']/?/?/button/div", ".//div[#'_hj_feedback_container']/?/?/button/div", 30000, null, "8a932f48-0d81-41d3-b641-33dabda18280");
                _errorfornameInfo = new RepoItemInfo(this, "ErrorForName", ".//div[#'error-for-name']", ".//div[#'error-for-name']", 30000, null, "242c1ae6-68b0-4386-be63-8095d988ecce");
                _errorforsurnameInfo = new RepoItemInfo(this, "ErrorForSurname", ".//div[#'error-for-surname']", ".//div[#'error-for-surname']", 30000, null, "32cd7ffb-4952-4554-a15b-79d7ed1bbd19");
                _errorforemailInfo = new RepoItemInfo(this, "ErrorForEmail", ".//div[#'error-for-email']", ".//div[#'error-for-email']", 30000, null, "baff8c52-0e40-4d66-975f-fa596649484d");
                _errorforpasswordInfo = new RepoItemInfo(this, "ErrorForPassword", ".//div[#'error-for-password']", ".//div[#'error-for-password']", 30000, null, "cd1621e6-e621-4a0b-83c8-763edd407814");
                _errorforpasswordconfirmedInfo = new RepoItemInfo(this, "ErrorForPasswordConfirmed", ".//div[#'error-for-passwordConfirmed']", ".//div[#'error-for-passwordConfirmed']", 30000, null, "5d2aacc3-f1ae-4939-8cc5-54651d0fd64d");
                _errorforphoneInfo = new RepoItemInfo(this, "ErrorForPhone", ".//div[#'error-for-phone']", ".//div[#'error-for-phone']", 30000, null, "6b243316-846a-4e62-80cc-a72cc4ff494b");
                _errorformembershipagreementInfo = new RepoItemInfo(this, "ErrorForMembershipAgreement", ".//div[#'error-for-membershipAgreement']", ".//div[#'error-for-membershipAgreement']", 30000, null, "5c5de42c-406e-4103-b68e-6275de92a832");
                _btnquicklk1Info = new RepoItemInfo(this, "BtnQuickLk1", ".//div[#'pagedListContainer']/div[4]/div[2]/div[1]//button/span[@innertext='HIZLI BAK']", ".//div[#'pagedListContainer']//span[@innertext='HIZLI BAK']", 30000, null, "1d57a512-60e4-4b06-854e-731c6c75d257");
                _btnaddbasket1Info = new RepoItemInfo(this, "BtnAddBasket1", ".//body[#'mainBody']/div[10]/div/div/div/div/div//form[@action='https://www.boyner.com.tr/kampanya/gift-card-c-3546632?story=e-gift&OM.zn=acttype-32&OM.zpc=act-152']/div[5]/div[1]/button[@innertext='Sepete Ekle']", ".//body[#'mainBody']//button[@innertext='Sepete Ekle']", 30000, null, "ecc18532-ca39-47fb-b215-a4791137cd09");
                _btnquicklk2Info = new RepoItemInfo(this, "BtnQuickLk2", ".//div[#'pagedListContainer']/div[4]/div[2]/div[2]//button", ".//div[#'pagedListContainer']/div[4]/div[2]/div[2]/div[1]/div[2]/div/div[1]/button", 30000, null, "92bcf9ce-2842-4adf-a68b-b00768ce8db2");
                _h1tagbasketcountInfo = new RepoItemInfo(this, "H1TagBasketCount", "body/div[1]/div[1]/div/div[1]/div[1]/h1[@innertext>'                Sepetim (2']", ".//h1[@innertext>'                Sepetim (2']", 30000, null, "479ccac0-f79e-4081-a879-f3b62fa9e67f");
                _btnbasketpageInfo = new RepoItemInfo(this, "BtnBasketPage", ".//body[#'mainBody']/div[1]/header/div[2]/div[1]/div[2]/div/div[3]/ul/li[4]/a[@href>'https://www.boyner.com.tr']", ".//body[#'mainBody']/?/?/header/div[2]/div[1]/div[2]/div/div[3]/ul/li[4]/a[@href>'https://www.boyner.com.tr']", 30000, null, "d65c8344-26fc-459f-8a6f-1117a84aff51");
                _basketitem1Info = new RepoItemInfo(this, "BasketItem1", "body/div[1]/div[1]/div/div[1]/div[2]", "body/div[1]/div[1]/div/div[1]/div[2]", 30000, null, "0c1eb676-4755-4d84-b765-cbd2a529292f");
                _basketitem2Info = new RepoItemInfo(this, "BasketItem2", "body/div[1]/div[1]/div/div[1]/div[3]", "body/div[1]/div[1]/div/div[1]/div[3]", 30000, null, "554d9969-3945-4711-81db-b3230714dc5a");
                _buttontaggirişInfo = new RepoItemInfo(this, "ButtonTagGiriş", ".///div[2]/div[5]/?/?/button[@innertext>'                        Giriş']", ".//form[#'loginForm']//button[@innertext>'                        Giriş']", 30000, null, "ac1b0f0b-afc8-4578-b2e7-3a63eb67a3bf");
                _customerpasswordInfo = new RepoItemInfo(this, "CustomerPassword", ".//input[#'customerPassword']", ".//input[#'customerPassword']", 30000, null, "bd39f293-09a4-4fd9-9dbf-6e21ac7bc49d");
                _customeremailInfo = new RepoItemInfo(this, "CustomerEmail", ".//input[#'customerEmail']", ".//input[#'customerEmail']", 30000, null, "98f4cc01-1892-45c9-8bed-bcc029cefc0d");
                _btnegiftInfo = new RepoItemInfo(this, "BtnEGift", ".//div[#'vl-story-wrapper']/div/div/div/div/div[16]/?/?/img[@alt='E-Gift']", ".//div[#'vl-story-wrapper']//img[@alt='E-Gift']", 30000, null, "61a603d0-d125-4572-b6b7-91384230d33a");
                _btnaddbasket2Info = new RepoItemInfo(this, "BtnAddBasket2", ".//body[#'mainBody']/div[11]/div/div/div/div/div//form[@action='https://www.boyner.com.tr/kampanya/gift-card-c-3546632?story=e-gift&OM.zn=acttype-32&OM.zpc=act-152']/div[5]/div[1]/button[@innertext='Sepete Ekle']/i", ".//body[#'mainBody']//button[@innertext='Sepete Ekle']/i", 30000, null, "aadad5c4-377e-4407-b3cd-f890e9c01f0e");
                _ostepitemInfo = new RepoItemInfo(this, "OStepItem", "body/div[1]//ul/li[1]", ".//ul/li[1]", 30000, null, "6144376f-df76-44a6-b0af-5ab7ce19129c");
                _ostepitem1Info = new RepoItemInfo(this, "OStepItem1", "body/div[1]//ul/li[2]", ".//ul/li[2]", 30000, null, "e1fa7f4f-702b-46f2-8bee-a41dddda33dd");
                _deliveryInfo = new RepoItemInfo(this, "Delivery", ".//section[#'delivery']", ".//section[#'delivery']", 30000, null, "5a6a9c61-7c0a-4c69-98fc-7862fb38aeac");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b3b7adfd-dc33-4b56-a07f-dd4cb5549ff1")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b3b7adfd-dc33-4b56-a07f-dd4cb5549ff1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HeaderContainerBoyner item.
            /// </summary>
            [RepositoryItem("72f3aad7-51af-4aa6-8357-9f0884410e17")]
            public virtual Ranorex.DivTag HeaderContainerBoyner
            {
                get
                {
                    return _headercontainerboynerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The HeaderContainerBoyner item info.
            /// </summary>
            [RepositoryItemInfo("72f3aad7-51af-4aa6-8357-9f0884410e17")]
            public virtual RepoItemInfo HeaderContainerBoynerInfo
            {
                get
                {
                    return _headercontainerboynerInfo;
                }
            }

            /// <summary>
            /// The BtnSignIn item.
            /// </summary>
            [RepositoryItem("a4613861-584d-4c54-bdf5-7f48629c6e10")]
            public virtual Ranorex.ButtonTag BtnSignIn
            {
                get
                {
                    return _btnsigninInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnSignIn item info.
            /// </summary>
            [RepositoryItemInfo("a4613861-584d-4c54-bdf5-7f48629c6e10")]
            public virtual RepoItemInfo BtnSignInInfo
            {
                get
                {
                    return _btnsigninInfo;
                }
            }

            /// <summary>
            /// The BtnRegister item.
            /// </summary>
            [RepositoryItem("7aa81104-95d8-4900-8f31-ba567f11d4cb")]
            public virtual Ranorex.ButtonTag BtnRegister
            {
                get
                {
                    return _btnregisterInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnRegister item info.
            /// </summary>
            [RepositoryItemInfo("7aa81104-95d8-4900-8f31-ba567f11d4cb")]
            public virtual RepoItemInfo BtnRegisterInfo
            {
                get
                {
                    return _btnregisterInfo;
                }
            }

            /// <summary>
            /// The HeaderUyeOl item.
            /// </summary>
            [RepositoryItem("a3cedfab-5eed-460b-b9d9-f05500f5e937")]
            public virtual Ranorex.SpanTag HeaderUyeOl
            {
                get
                {
                    return _headeruyeolInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The HeaderUyeOl item info.
            /// </summary>
            [RepositoryItemInfo("a3cedfab-5eed-460b-b9d9-f05500f5e937")]
            public virtual RepoItemInfo HeaderUyeOlInfo
            {
                get
                {
                    return _headeruyeolInfo;
                }
            }

            /// <summary>
            /// The FieldName item.
            /// </summary>
            [RepositoryItem("e41ac9c3-3d07-4623-baee-d964dd083914")]
            public virtual Ranorex.InputTag FieldName
            {
                get
                {
                    return _fieldnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FieldName item info.
            /// </summary>
            [RepositoryItemInfo("e41ac9c3-3d07-4623-baee-d964dd083914")]
            public virtual RepoItemInfo FieldNameInfo
            {
                get
                {
                    return _fieldnameInfo;
                }
            }

            /// <summary>
            /// The FieldSurname item.
            /// </summary>
            [RepositoryItem("9cda977a-8125-4bca-b7cf-02f1fd3cf319")]
            public virtual Ranorex.InputTag FieldSurname
            {
                get
                {
                    return _fieldsurnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FieldSurname item info.
            /// </summary>
            [RepositoryItemInfo("9cda977a-8125-4bca-b7cf-02f1fd3cf319")]
            public virtual RepoItemInfo FieldSurnameInfo
            {
                get
                {
                    return _fieldsurnameInfo;
                }
            }

            /// <summary>
            /// The FieldEmail item.
            /// </summary>
            [RepositoryItem("6d18d7b5-1efc-4cdb-87c3-de11c44621a6")]
            public virtual Ranorex.InputTag FieldEmail
            {
                get
                {
                    return _fieldemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FieldEmail item info.
            /// </summary>
            [RepositoryItemInfo("6d18d7b5-1efc-4cdb-87c3-de11c44621a6")]
            public virtual RepoItemInfo FieldEmailInfo
            {
                get
                {
                    return _fieldemailInfo;
                }
            }

            /// <summary>
            /// The FieldPassword item.
            /// </summary>
            [RepositoryItem("3e4e9a1b-6502-42d8-a8fe-f36571d65ce5")]
            public virtual Ranorex.InputTag FieldPassword
            {
                get
                {
                    return _fieldpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FieldPassword item info.
            /// </summary>
            [RepositoryItemInfo("3e4e9a1b-6502-42d8-a8fe-f36571d65ce5")]
            public virtual RepoItemInfo FieldPasswordInfo
            {
                get
                {
                    return _fieldpasswordInfo;
                }
            }

            /// <summary>
            /// The FieldPasswordConfirmed item.
            /// </summary>
            [RepositoryItem("4059b3b9-eb82-4269-9cfc-21b4f4936325")]
            public virtual Ranorex.InputTag FieldPasswordConfirmed
            {
                get
                {
                    return _fieldpasswordconfirmedInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FieldPasswordConfirmed item info.
            /// </summary>
            [RepositoryItemInfo("4059b3b9-eb82-4269-9cfc-21b4f4936325")]
            public virtual RepoItemInfo FieldPasswordConfirmedInfo
            {
                get
                {
                    return _fieldpasswordconfirmedInfo;
                }
            }

            /// <summary>
            /// The FieldPhone item.
            /// </summary>
            [RepositoryItem("67c71b35-1e5b-4ab8-accd-0b5f127ac1e9")]
            public virtual Ranorex.InputTag FieldPhone
            {
                get
                {
                    return _fieldphoneInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FieldPhone item info.
            /// </summary>
            [RepositoryItemInfo("67c71b35-1e5b-4ab8-accd-0b5f127ac1e9")]
            public virtual RepoItemInfo FieldPhoneInfo
            {
                get
                {
                    return _fieldphoneInfo;
                }
            }

            /// <summary>
            /// The BtnFeedback item.
            /// </summary>
            [RepositoryItem("8a932f48-0d81-41d3-b641-33dabda18280")]
            public virtual Ranorex.DivTag BtnFeedback
            {
                get
                {
                    return _btnfeedbackInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The BtnFeedback item info.
            /// </summary>
            [RepositoryItemInfo("8a932f48-0d81-41d3-b641-33dabda18280")]
            public virtual RepoItemInfo BtnFeedbackInfo
            {
                get
                {
                    return _btnfeedbackInfo;
                }
            }

            /// <summary>
            /// The ErrorForName item.
            /// </summary>
            [RepositoryItem("242c1ae6-68b0-4386-be63-8095d988ecce")]
            public virtual Ranorex.DivTag ErrorForName
            {
                get
                {
                    return _errorfornameInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ErrorForName item info.
            /// </summary>
            [RepositoryItemInfo("242c1ae6-68b0-4386-be63-8095d988ecce")]
            public virtual RepoItemInfo ErrorForNameInfo
            {
                get
                {
                    return _errorfornameInfo;
                }
            }

            /// <summary>
            /// The ErrorForSurname item.
            /// </summary>
            [RepositoryItem("32cd7ffb-4952-4554-a15b-79d7ed1bbd19")]
            public virtual Ranorex.DivTag ErrorForSurname
            {
                get
                {
                    return _errorforsurnameInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ErrorForSurname item info.
            /// </summary>
            [RepositoryItemInfo("32cd7ffb-4952-4554-a15b-79d7ed1bbd19")]
            public virtual RepoItemInfo ErrorForSurnameInfo
            {
                get
                {
                    return _errorforsurnameInfo;
                }
            }

            /// <summary>
            /// The ErrorForEmail item.
            /// </summary>
            [RepositoryItem("baff8c52-0e40-4d66-975f-fa596649484d")]
            public virtual Ranorex.DivTag ErrorForEmail
            {
                get
                {
                    return _errorforemailInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ErrorForEmail item info.
            /// </summary>
            [RepositoryItemInfo("baff8c52-0e40-4d66-975f-fa596649484d")]
            public virtual RepoItemInfo ErrorForEmailInfo
            {
                get
                {
                    return _errorforemailInfo;
                }
            }

            /// <summary>
            /// The ErrorForPassword item.
            /// </summary>
            [RepositoryItem("cd1621e6-e621-4a0b-83c8-763edd407814")]
            public virtual Ranorex.DivTag ErrorForPassword
            {
                get
                {
                    return _errorforpasswordInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ErrorForPassword item info.
            /// </summary>
            [RepositoryItemInfo("cd1621e6-e621-4a0b-83c8-763edd407814")]
            public virtual RepoItemInfo ErrorForPasswordInfo
            {
                get
                {
                    return _errorforpasswordInfo;
                }
            }

            /// <summary>
            /// The ErrorForPasswordConfirmed item.
            /// </summary>
            [RepositoryItem("5d2aacc3-f1ae-4939-8cc5-54651d0fd64d")]
            public virtual Ranorex.DivTag ErrorForPasswordConfirmed
            {
                get
                {
                    return _errorforpasswordconfirmedInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ErrorForPasswordConfirmed item info.
            /// </summary>
            [RepositoryItemInfo("5d2aacc3-f1ae-4939-8cc5-54651d0fd64d")]
            public virtual RepoItemInfo ErrorForPasswordConfirmedInfo
            {
                get
                {
                    return _errorforpasswordconfirmedInfo;
                }
            }

            /// <summary>
            /// The ErrorForPhone item.
            /// </summary>
            [RepositoryItem("6b243316-846a-4e62-80cc-a72cc4ff494b")]
            public virtual Ranorex.DivTag ErrorForPhone
            {
                get
                {
                    return _errorforphoneInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ErrorForPhone item info.
            /// </summary>
            [RepositoryItemInfo("6b243316-846a-4e62-80cc-a72cc4ff494b")]
            public virtual RepoItemInfo ErrorForPhoneInfo
            {
                get
                {
                    return _errorforphoneInfo;
                }
            }

            /// <summary>
            /// The ErrorForMembershipAgreement item.
            /// </summary>
            [RepositoryItem("5c5de42c-406e-4103-b68e-6275de92a832")]
            public virtual Ranorex.DivTag ErrorForMembershipAgreement
            {
                get
                {
                    return _errorformembershipagreementInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ErrorForMembershipAgreement item info.
            /// </summary>
            [RepositoryItemInfo("5c5de42c-406e-4103-b68e-6275de92a832")]
            public virtual RepoItemInfo ErrorForMembershipAgreementInfo
            {
                get
                {
                    return _errorformembershipagreementInfo;
                }
            }

            /// <summary>
            /// The BtnQuickLk1 item.
            /// </summary>
            [RepositoryItem("1d57a512-60e4-4b06-854e-731c6c75d257")]
            public virtual Ranorex.SpanTag BtnQuickLk1
            {
                get
                {
                    return _btnquicklk1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The BtnQuickLk1 item info.
            /// </summary>
            [RepositoryItemInfo("1d57a512-60e4-4b06-854e-731c6c75d257")]
            public virtual RepoItemInfo BtnQuickLk1Info
            {
                get
                {
                    return _btnquicklk1Info;
                }
            }

            /// <summary>
            /// The BtnAddBasket1 item.
            /// </summary>
            [RepositoryItem("ecc18532-ca39-47fb-b215-a4791137cd09")]
            public virtual Ranorex.ButtonTag BtnAddBasket1
            {
                get
                {
                    return _btnaddbasket1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnAddBasket1 item info.
            /// </summary>
            [RepositoryItemInfo("ecc18532-ca39-47fb-b215-a4791137cd09")]
            public virtual RepoItemInfo BtnAddBasket1Info
            {
                get
                {
                    return _btnaddbasket1Info;
                }
            }

            /// <summary>
            /// The BtnQuickLk2 item.
            /// </summary>
            [RepositoryItem("92bcf9ce-2842-4adf-a68b-b00768ce8db2")]
            public virtual Ranorex.ButtonTag BtnQuickLk2
            {
                get
                {
                    return _btnquicklk2Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnQuickLk2 item info.
            /// </summary>
            [RepositoryItemInfo("92bcf9ce-2842-4adf-a68b-b00768ce8db2")]
            public virtual RepoItemInfo BtnQuickLk2Info
            {
                get
                {
                    return _btnquicklk2Info;
                }
            }

            /// <summary>
            /// The H1TagBasketCount item.
            /// </summary>
            [RepositoryItem("479ccac0-f79e-4081-a879-f3b62fa9e67f")]
            public virtual Ranorex.H1Tag H1TagBasketCount
            {
                get
                {
                    return _h1tagbasketcountInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The H1TagBasketCount item info.
            /// </summary>
            [RepositoryItemInfo("479ccac0-f79e-4081-a879-f3b62fa9e67f")]
            public virtual RepoItemInfo H1TagBasketCountInfo
            {
                get
                {
                    return _h1tagbasketcountInfo;
                }
            }

            /// <summary>
            /// The BtnBasketPage item.
            /// </summary>
            [RepositoryItem("d65c8344-26fc-459f-8a6f-1117a84aff51")]
            public virtual Ranorex.ATag BtnBasketPage
            {
                get
                {
                    return _btnbasketpageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BtnBasketPage item info.
            /// </summary>
            [RepositoryItemInfo("d65c8344-26fc-459f-8a6f-1117a84aff51")]
            public virtual RepoItemInfo BtnBasketPageInfo
            {
                get
                {
                    return _btnbasketpageInfo;
                }
            }

            /// <summary>
            /// The BasketItem1 item.
            /// </summary>
            [RepositoryItem("0c1eb676-4755-4d84-b765-cbd2a529292f")]
            public virtual Ranorex.DivTag BasketItem1
            {
                get
                {
                    return _basketitem1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The BasketItem1 item info.
            /// </summary>
            [RepositoryItemInfo("0c1eb676-4755-4d84-b765-cbd2a529292f")]
            public virtual RepoItemInfo BasketItem1Info
            {
                get
                {
                    return _basketitem1Info;
                }
            }

            /// <summary>
            /// The BasketItem2 item.
            /// </summary>
            [RepositoryItem("554d9969-3945-4711-81db-b3230714dc5a")]
            public virtual Ranorex.DivTag BasketItem2
            {
                get
                {
                    return _basketitem2Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The BasketItem2 item info.
            /// </summary>
            [RepositoryItemInfo("554d9969-3945-4711-81db-b3230714dc5a")]
            public virtual RepoItemInfo BasketItem2Info
            {
                get
                {
                    return _basketitem2Info;
                }
            }

            /// <summary>
            /// The ButtonTagGiriş item.
            /// </summary>
            [RepositoryItem("ac1b0f0b-afc8-4578-b2e7-3a63eb67a3bf")]
            public virtual Ranorex.ButtonTag ButtonTagGiriş
            {
                get
                {
                    return _buttontaggirişInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagGiriş item info.
            /// </summary>
            [RepositoryItemInfo("ac1b0f0b-afc8-4578-b2e7-3a63eb67a3bf")]
            public virtual RepoItemInfo ButtonTagGirişInfo
            {
                get
                {
                    return _buttontaggirişInfo;
                }
            }

            /// <summary>
            /// The CustomerPassword item.
            /// </summary>
            [RepositoryItem("bd39f293-09a4-4fd9-9dbf-6e21ac7bc49d")]
            public virtual Ranorex.InputTag CustomerPassword
            {
                get
                {
                    return _customerpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CustomerPassword item info.
            /// </summary>
            [RepositoryItemInfo("bd39f293-09a4-4fd9-9dbf-6e21ac7bc49d")]
            public virtual RepoItemInfo CustomerPasswordInfo
            {
                get
                {
                    return _customerpasswordInfo;
                }
            }

            /// <summary>
            /// The CustomerEmail item.
            /// </summary>
            [RepositoryItem("98f4cc01-1892-45c9-8bed-bcc029cefc0d")]
            public virtual Ranorex.InputTag CustomerEmail
            {
                get
                {
                    return _customeremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CustomerEmail item info.
            /// </summary>
            [RepositoryItemInfo("98f4cc01-1892-45c9-8bed-bcc029cefc0d")]
            public virtual RepoItemInfo CustomerEmailInfo
            {
                get
                {
                    return _customeremailInfo;
                }
            }

            /// <summary>
            /// The BtnEGift item.
            /// </summary>
            [RepositoryItem("61a603d0-d125-4572-b6b7-91384230d33a")]
            public virtual Ranorex.ImgTag BtnEGift
            {
                get
                {
                    return _btnegiftInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The BtnEGift item info.
            /// </summary>
            [RepositoryItemInfo("61a603d0-d125-4572-b6b7-91384230d33a")]
            public virtual RepoItemInfo BtnEGiftInfo
            {
                get
                {
                    return _btnegiftInfo;
                }
            }

            /// <summary>
            /// The BtnAddBasket2 item.
            /// </summary>
            [RepositoryItem("aadad5c4-377e-4407-b3cd-f890e9c01f0e")]
            public virtual Ranorex.ITag BtnAddBasket2
            {
                get
                {
                    return _btnaddbasket2Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The BtnAddBasket2 item info.
            /// </summary>
            [RepositoryItemInfo("aadad5c4-377e-4407-b3cd-f890e9c01f0e")]
            public virtual RepoItemInfo BtnAddBasket2Info
            {
                get
                {
                    return _btnaddbasket2Info;
                }
            }

            /// <summary>
            /// The OStepItem item.
            /// </summary>
            [RepositoryItem("6144376f-df76-44a6-b0af-5ab7ce19129c")]
            public virtual Ranorex.LiTag OStepItem
            {
                get
                {
                    return _ostepitemInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The OStepItem item info.
            /// </summary>
            [RepositoryItemInfo("6144376f-df76-44a6-b0af-5ab7ce19129c")]
            public virtual RepoItemInfo OStepItemInfo
            {
                get
                {
                    return _ostepitemInfo;
                }
            }

            /// <summary>
            /// The OStepItem1 item.
            /// </summary>
            [RepositoryItem("e1fa7f4f-702b-46f2-8bee-a41dddda33dd")]
            public virtual Ranorex.LiTag OStepItem1
            {
                get
                {
                    return _ostepitem1Info.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The OStepItem1 item info.
            /// </summary>
            [RepositoryItemInfo("e1fa7f4f-702b-46f2-8bee-a41dddda33dd")]
            public virtual RepoItemInfo OStepItem1Info
            {
                get
                {
                    return _ostepitem1Info;
                }
            }

            /// <summary>
            /// The Delivery item.
            /// </summary>
            [RepositoryItem("5a6a9c61-7c0a-4c69-98fc-7862fb38aeac")]
            public virtual Ranorex.SectionTag Delivery
            {
                get
                {
                    return _deliveryInfo.CreateAdapter<Ranorex.SectionTag>(true);
                }
            }

            /// <summary>
            /// The Delivery item info.
            /// </summary>
            [RepositoryItemInfo("5a6a9c61-7c0a-4c69-98fc-7862fb38aeac")]
            public virtual RepoItemInfo DeliveryInfo
            {
                get
                {
                    return _deliveryInfo;
                }
            }

            /// <summary>
            /// The RegisterForm folder.
            /// </summary>
            [RepositoryFolder("173eddea-f8f1-46cc-924b-8dcf09a117a9")]
            public virtual Test_CaseRepositoryFolders.RegisterFormFolder RegisterForm
            {
                get { return _registerform; }
            }

            /// <summary>
            /// The ProductList folder.
            /// </summary>
            [RepositoryFolder("44ea5893-9fb5-4790-b9fb-b6bb10455554")]
            public virtual Test_CaseRepositoryFolders.ProductListFolder ProductList
            {
                get { return _productlist; }
            }

            /// <summary>
            /// The PageWrapper folder.
            /// </summary>
            [RepositoryFolder("904a1892-6d65-4918-82a6-ba129017f21b")]
            public virtual Test_CaseRepositoryFolders.PageWrapperFolder PageWrapper
            {
                get { return _pagewrapper; }
            }

            /// <summary>
            /// The DivTagRow folder.
            /// </summary>
            [RepositoryFolder("946e5a7a-6111-482a-b10d-17d676db1f4a")]
            public virtual Test_CaseRepositoryFolders.DivTagRowFolder DivTagRow
            {
                get { return _divtagrow; }
            }
        }

        /// <summary>
        /// The RegisterFormFolder folder.
        /// </summary>
        [RepositoryFolder("173eddea-f8f1-46cc-924b-8dcf09a117a9")]
        public partial class RegisterFormFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selectgenderInfo;
            RepoItemInfo _selectdayInfo;
            RepoItemInfo _selectmonthInfo;
            RepoItemInfo _selectyearInfo;
            RepoItemInfo _textclarificationInfo;
            RepoItemInfo _chkboxconfirmationInfo;
            RepoItemInfo _chkboxpermitInfo;
            RepoItemInfo _textrecaptchaInfo;
            RepoItemInfo _btnsubmitInfo;
            RepoItemInfo _customcheckboxlabelInfo;
            RepoItemInfo _customcheckboxlabel1Info;
            RepoItemInfo _headerusermenuInfo;
            RepoItemInfo _ueyelikbilgilerimiveiletişimizinleriInfo;

            /// <summary>
            /// Creates a new RegisterForm  folder.
            /// </summary>
            public RegisterFormFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterForm", ".//", parentFolder, 30000, null, false, "173eddea-f8f1-46cc-924b-8dcf09a117a9", "")
            {
                _selectgenderInfo = new RepoItemInfo(this, "SelectGender", "div[2]/div[5]/?/?/select[@name='RegisterModel_main_genderid']", "form[#'registerForm']//select[@name='RegisterModel_main_genderid']", 30000, null, "a76c90eb-cd69-4a9e-88b2-7a264ba3c909");
                _selectdayInfo = new RepoItemInfo(this, "SelectDay", "div[2]/div[6]/?/?/select[@name='RegisterModel_main_day']", "form[#'registerForm']//select[@name='RegisterModel_main_day']", 30000, null, "7c75c376-f13a-4ea0-8eb6-bd82bbd805a2");
                _selectmonthInfo = new RepoItemInfo(this, "SelectMonth", "div[2]/div[6]/?/?/select[@name='RegisterModel_main_month']", "form[#'registerForm']//select[@name='RegisterModel_main_month']", 30000, null, "bba7a94d-8561-489c-932a-6ef87a7686c9");
                _selectyearInfo = new RepoItemInfo(this, "SelectYear", "div[2]/div[6]/?/?/select[@name='RegisterModel_main_year']", "form[#'registerForm']//select[@name='RegisterModel_main_year']", 30000, null, "b42c822d-34fd-470e-96c0-1a029fb7e766");
                _textclarificationInfo = new RepoItemInfo(this, "TextClarification", "div[2]/div[7]//span[@innertext>'']", "form[#'registerForm']//span[@innertext>'']", 30000, null, "7d9d300d-c6a8-4e12-9fd9-8abec5acbd68");
                _chkboxconfirmationInfo = new RepoItemInfo(this, "ChkBoxConfirmation", "div[2]/div[8]//span[@innertext>' ve']", "form[#'registerForm']//span[@innertext>' ve']", 30000, null, "f3f91cbb-74b0-4630-9cd4-fc17b6a944cf");
                _chkboxpermitInfo = new RepoItemInfo(this, "ChkBoxPermit", "div[2]/div[9]//span[@innertext>'']", "form[#'registerForm']/div[2]/div[9]/div/div/label/span[@innertext>'']", 30000, null, "5edcc193-b5a3-4dd9-982e-7223d621ae4f");
                _textrecaptchaInfo = new RepoItemInfo(this, "TextReCaptcha", "?/?/div[@innertext>'Bu sayfa reCAPTCHA tarafından']", "form[#'registerForm']/?/?/div[@innertext>'Bu sayfa reCAPTCHA tarafından']", 30000, null, "3996232e-e488-4b6c-8e97-0f629df97961");
                _btnsubmitInfo = new RepoItemInfo(this, "BtnSubmit", "div[2]/div[11]/?/?/button[@innertext>'                        Üyeliği']", "form[#'registerForm']//button[@innertext>'                        Üyeliği']", 30000, null, "9dbcf1e7-1ca6-4d8f-8309-ba378d22a2bf");
                _customcheckboxlabelInfo = new RepoItemInfo(this, "CustomCheckboxLabel", "div[2]/div[8]//label", "form[#'registerForm']/div[2]/div[8]/div/div/label", 30000, null, "689785df-80b2-4f11-89a7-eae6bf1860be");
                _customcheckboxlabel1Info = new RepoItemInfo(this, "CustomCheckboxLabel1", "div[2]/div[9]//label", "form[#'registerForm']/div[2]/div[9]/div/div/label", 30000, null, "8407d2ec-d117-4708-8bf4-61483e21d091");
                _headerusermenuInfo = new RepoItemInfo(this, "HeaderUserMenu", "body[#'mainBody']/div[1]/header/div[2]/div[1]/div[2]/div/div[3]", "body[#'mainBody']/?/?/header/div[2]/div[1]/div[2]/div/div[3]", 30000, null, "1af9af57-699d-41ac-b1bf-a323a7d4d3bf");
                _ueyelikbilgilerimiveiletişimizinleriInfo = new RepoItemInfo(this, "UEyelikBilgilerimiVeIletişimIzinleri", "body[#'mainBody']/div[1]//section/div[2]/div/div[1]/div[@innertext>'Üyelik bilgilerimi ve iletişim']", "body[#'mainBody']//div[@innertext>'Üyelik bilgilerimi ve iletişim']", 30000, null, "a2cf0d5f-c249-4894-9a28-485d83c4cdac");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("173eddea-f8f1-46cc-924b-8dcf09a117a9")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("173eddea-f8f1-46cc-924b-8dcf09a117a9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SelectGender item.
            /// </summary>
            [RepositoryItem("a76c90eb-cd69-4a9e-88b2-7a264ba3c909")]
            public virtual Ranorex.SelectTag SelectGender
            {
                get
                {
                    return _selectgenderInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The SelectGender item info.
            /// </summary>
            [RepositoryItemInfo("a76c90eb-cd69-4a9e-88b2-7a264ba3c909")]
            public virtual RepoItemInfo SelectGenderInfo
            {
                get
                {
                    return _selectgenderInfo;
                }
            }

            /// <summary>
            /// The SelectDay item.
            /// </summary>
            [RepositoryItem("7c75c376-f13a-4ea0-8eb6-bd82bbd805a2")]
            public virtual Ranorex.SelectTag SelectDay
            {
                get
                {
                    return _selectdayInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The SelectDay item info.
            /// </summary>
            [RepositoryItemInfo("7c75c376-f13a-4ea0-8eb6-bd82bbd805a2")]
            public virtual RepoItemInfo SelectDayInfo
            {
                get
                {
                    return _selectdayInfo;
                }
            }

            /// <summary>
            /// The SelectMonth item.
            /// </summary>
            [RepositoryItem("bba7a94d-8561-489c-932a-6ef87a7686c9")]
            public virtual Ranorex.SelectTag SelectMonth
            {
                get
                {
                    return _selectmonthInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The SelectMonth item info.
            /// </summary>
            [RepositoryItemInfo("bba7a94d-8561-489c-932a-6ef87a7686c9")]
            public virtual RepoItemInfo SelectMonthInfo
            {
                get
                {
                    return _selectmonthInfo;
                }
            }

            /// <summary>
            /// The SelectYear item.
            /// </summary>
            [RepositoryItem("b42c822d-34fd-470e-96c0-1a029fb7e766")]
            public virtual Ranorex.SelectTag SelectYear
            {
                get
                {
                    return _selectyearInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The SelectYear item info.
            /// </summary>
            [RepositoryItemInfo("b42c822d-34fd-470e-96c0-1a029fb7e766")]
            public virtual RepoItemInfo SelectYearInfo
            {
                get
                {
                    return _selectyearInfo;
                }
            }

            /// <summary>
            /// The TextClarification item.
            /// </summary>
            [RepositoryItem("7d9d300d-c6a8-4e12-9fd9-8abec5acbd68")]
            public virtual Ranorex.SpanTag TextClarification
            {
                get
                {
                    return _textclarificationInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TextClarification item info.
            /// </summary>
            [RepositoryItemInfo("7d9d300d-c6a8-4e12-9fd9-8abec5acbd68")]
            public virtual RepoItemInfo TextClarificationInfo
            {
                get
                {
                    return _textclarificationInfo;
                }
            }

            /// <summary>
            /// The ChkBoxConfirmation item.
            /// </summary>
            [RepositoryItem("f3f91cbb-74b0-4630-9cd4-fc17b6a944cf")]
            public virtual Ranorex.SpanTag ChkBoxConfirmation
            {
                get
                {
                    return _chkboxconfirmationInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ChkBoxConfirmation item info.
            /// </summary>
            [RepositoryItemInfo("f3f91cbb-74b0-4630-9cd4-fc17b6a944cf")]
            public virtual RepoItemInfo ChkBoxConfirmationInfo
            {
                get
                {
                    return _chkboxconfirmationInfo;
                }
            }

            /// <summary>
            /// The ChkBoxPermit item.
            /// </summary>
            [RepositoryItem("5edcc193-b5a3-4dd9-982e-7223d621ae4f")]
            public virtual Ranorex.SpanTag ChkBoxPermit
            {
                get
                {
                    return _chkboxpermitInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ChkBoxPermit item info.
            /// </summary>
            [RepositoryItemInfo("5edcc193-b5a3-4dd9-982e-7223d621ae4f")]
            public virtual RepoItemInfo ChkBoxPermitInfo
            {
                get
                {
                    return _chkboxpermitInfo;
                }
            }

            /// <summary>
            /// The TextReCaptcha item.
            /// </summary>
            [RepositoryItem("3996232e-e488-4b6c-8e97-0f629df97961")]
            public virtual Ranorex.DivTag TextReCaptcha
            {
                get
                {
                    return _textrecaptchaInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The TextReCaptcha item info.
            /// </summary>
            [RepositoryItemInfo("3996232e-e488-4b6c-8e97-0f629df97961")]
            public virtual RepoItemInfo TextReCaptchaInfo
            {
                get
                {
                    return _textrecaptchaInfo;
                }
            }

            /// <summary>
            /// The BtnSubmit item.
            /// </summary>
            [RepositoryItem("9dbcf1e7-1ca6-4d8f-8309-ba378d22a2bf")]
            public virtual Ranorex.ButtonTag BtnSubmit
            {
                get
                {
                    return _btnsubmitInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnSubmit item info.
            /// </summary>
            [RepositoryItemInfo("9dbcf1e7-1ca6-4d8f-8309-ba378d22a2bf")]
            public virtual RepoItemInfo BtnSubmitInfo
            {
                get
                {
                    return _btnsubmitInfo;
                }
            }

            /// <summary>
            /// The CustomCheckboxLabel item.
            /// </summary>
            [RepositoryItem("689785df-80b2-4f11-89a7-eae6bf1860be")]
            public virtual Ranorex.LabelTag CustomCheckboxLabel
            {
                get
                {
                    return _customcheckboxlabelInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The CustomCheckboxLabel item info.
            /// </summary>
            [RepositoryItemInfo("689785df-80b2-4f11-89a7-eae6bf1860be")]
            public virtual RepoItemInfo CustomCheckboxLabelInfo
            {
                get
                {
                    return _customcheckboxlabelInfo;
                }
            }

            /// <summary>
            /// The CustomCheckboxLabel1 item.
            /// </summary>
            [RepositoryItem("8407d2ec-d117-4708-8bf4-61483e21d091")]
            public virtual Ranorex.LabelTag CustomCheckboxLabel1
            {
                get
                {
                    return _customcheckboxlabel1Info.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The CustomCheckboxLabel1 item info.
            /// </summary>
            [RepositoryItemInfo("8407d2ec-d117-4708-8bf4-61483e21d091")]
            public virtual RepoItemInfo CustomCheckboxLabel1Info
            {
                get
                {
                    return _customcheckboxlabel1Info;
                }
            }

            /// <summary>
            /// The HeaderUserMenu item.
            /// </summary>
            [RepositoryItem("1af9af57-699d-41ac-b1bf-a323a7d4d3bf")]
            public virtual Ranorex.DivTag HeaderUserMenu
            {
                get
                {
                    return _headerusermenuInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The HeaderUserMenu item info.
            /// </summary>
            [RepositoryItemInfo("1af9af57-699d-41ac-b1bf-a323a7d4d3bf")]
            public virtual RepoItemInfo HeaderUserMenuInfo
            {
                get
                {
                    return _headerusermenuInfo;
                }
            }

            /// <summary>
            /// The UEyelikBilgilerimiVeIletişimIzinleri item.
            /// </summary>
            [RepositoryItem("a2cf0d5f-c249-4894-9a28-485d83c4cdac")]
            public virtual Ranorex.DivTag UEyelikBilgilerimiVeIletişimIzinleri
            {
                get
                {
                    return _ueyelikbilgilerimiveiletişimizinleriInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The UEyelikBilgilerimiVeIletişimIzinleri item info.
            /// </summary>
            [RepositoryItemInfo("a2cf0d5f-c249-4894-9a28-485d83c4cdac")]
            public virtual RepoItemInfo UEyelikBilgilerimiVeIletişimIzinleriInfo
            {
                get
                {
                    return _ueyelikbilgilerimiveiletişimizinleriInfo;
                }
            }
        }

        /// <summary>
        /// The ProductListFolder folder.
        /// </summary>
        [RepositoryFolder("44ea5893-9fb5-4790-b9fb-b6bb10455554")]
        public partial class ProductListFolder : RepoGenBaseFolder
        {
            RepoItemInfo _product1Info;
            RepoItemInfo _btnquicklk2Info;
            RepoItemInfo _product2Info;
            RepoItemInfo _btnaddfav1Info;
            RepoItemInfo _btnaddfav2Info;

            /// <summary>
            /// Creates a new ProductList  folder.
            /// </summary>
            public ProductListFolder(RepoGenBaseFolder parentFolder) :
                    base("ProductList", ".//div[#'pagedListContainer']/div[4]/div[2]", parentFolder, 30000, null, false, "44ea5893-9fb5-4790-b9fb-b6bb10455554", "")
            {
                _product1Info = new RepoItemInfo(this, "Product1", "div[1]/?/?/a[@href>'https://www.boyner.com.tr']/div[2]", "div[2]", 30000, null, "4901e766-af09-4e47-ab3b-015f4fffc636");
                _btnquicklk2Info = new RepoItemInfo(this, "BtnQuickLk2", "div[2]//button/span[@innertext='HIZLI BAK']", "div[2]/div[1]/div[2]/div/div[1]/button/span[@innertext='HIZLI BAK']", 30000, null, "3501d941-5aa6-4d1a-81f3-05adb6b152b4");
                _product2Info = new RepoItemInfo(this, "Product2", "div[2]/?/?/a[@href>'https://www.boyner.com.tr']/div[2]", "div[2]/div[1]/a[@href>'https://www.boyner.com.tr']/div[2]", 30000, null, "c18eb5db-b258-4147-9801-fb18a7c2d258");
                _btnaddfav1Info = new RepoItemInfo(this, "BtnAddFav1", "div[1]/div[1]/div[2]/div/div[2]/a[@href>'https://www.boyner.com.tr']/i", "div[1]/div[1]/div[2]/div/div[2]/a[@href>'https://www.boyner.com.tr']/i", 30000, null, "99a3c376-8bf2-45f7-a8d1-dea64283c392");
                _btnaddfav2Info = new RepoItemInfo(this, "BtnAddFav2", "div[2]/div[1]/div[2]/div/div[2]/a[@href>'https://www.boyner.com.tr']/i", "div[2]/div[1]/div[2]/div/div[2]/a[@href>'https://www.boyner.com.tr']/i", 30000, null, "96cb296d-d8c6-4f87-b473-e14813ce5665");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("44ea5893-9fb5-4790-b9fb-b6bb10455554")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("44ea5893-9fb5-4790-b9fb-b6bb10455554")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Product1 item.
            /// </summary>
            [RepositoryItem("4901e766-af09-4e47-ab3b-015f4fffc636")]
            public virtual Ranorex.DivTag Product1
            {
                get
                {
                    return _product1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Product1 item info.
            /// </summary>
            [RepositoryItemInfo("4901e766-af09-4e47-ab3b-015f4fffc636")]
            public virtual RepoItemInfo Product1Info
            {
                get
                {
                    return _product1Info;
                }
            }

            /// <summary>
            /// The BtnQuickLk2 item.
            /// </summary>
            [RepositoryItem("3501d941-5aa6-4d1a-81f3-05adb6b152b4")]
            public virtual Ranorex.SpanTag BtnQuickLk2
            {
                get
                {
                    return _btnquicklk2Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The BtnQuickLk2 item info.
            /// </summary>
            [RepositoryItemInfo("3501d941-5aa6-4d1a-81f3-05adb6b152b4")]
            public virtual RepoItemInfo BtnQuickLk2Info
            {
                get
                {
                    return _btnquicklk2Info;
                }
            }

            /// <summary>
            /// The Product2 item.
            /// </summary>
            [RepositoryItem("c18eb5db-b258-4147-9801-fb18a7c2d258")]
            public virtual Ranorex.DivTag Product2
            {
                get
                {
                    return _product2Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Product2 item info.
            /// </summary>
            [RepositoryItemInfo("c18eb5db-b258-4147-9801-fb18a7c2d258")]
            public virtual RepoItemInfo Product2Info
            {
                get
                {
                    return _product2Info;
                }
            }

            /// <summary>
            /// The BtnAddFav1 item.
            /// </summary>
            [RepositoryItem("99a3c376-8bf2-45f7-a8d1-dea64283c392")]
            public virtual Ranorex.ITag BtnAddFav1
            {
                get
                {
                    return _btnaddfav1Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The BtnAddFav1 item info.
            /// </summary>
            [RepositoryItemInfo("99a3c376-8bf2-45f7-a8d1-dea64283c392")]
            public virtual RepoItemInfo BtnAddFav1Info
            {
                get
                {
                    return _btnaddfav1Info;
                }
            }

            /// <summary>
            /// The BtnAddFav2 item.
            /// </summary>
            [RepositoryItem("96cb296d-d8c6-4f87-b473-e14813ce5665")]
            public virtual Ranorex.ITag BtnAddFav2
            {
                get
                {
                    return _btnaddfav2Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The BtnAddFav2 item info.
            /// </summary>
            [RepositoryItemInfo("96cb296d-d8c6-4f87-b473-e14813ce5665")]
            public virtual RepoItemInfo BtnAddFav2Info
            {
                get
                {
                    return _btnaddfav2Info;
                }
            }
        }

        /// <summary>
        /// The PageWrapperFolder folder.
        /// </summary>
        [RepositoryFolder("904a1892-6d65-4918-82a6-ba129017f21b")]
        public partial class PageWrapperFolder : RepoGenBaseFolder
        {
            RepoItemInfo _spantagdijitalgiftcard25Info;
            RepoItemInfo _spantagdijitalgiftcard50Info;
            RepoItemInfo _headeruyegirisiInfo;
            RepoItemInfo _testtestInfo;
            RepoItemInfo _btnfavpageInfo;
            RepoItemInfo _personalfavorite1Info;
            RepoItemInfo _btnuserInfo;
            RepoItemInfo _btnfavoritesInfo;
            RepoItemInfo _btnbasketInfo;
            RepoItemInfo _btnsignoutInfo;
            RepoItemInfo _yardımInfo;
            RepoItemInfo _spantag300tlplusalışverişlerinizdeueInfo;
            RepoItemInfo _yardimInfo;

            /// <summary>
            /// Creates a new PageWrapper  folder.
            /// </summary>
            public PageWrapperFolder(RepoGenBaseFolder parentFolder) :
                    base("PageWrapper", ".//body[#'mainBody']/div[1]", parentFolder, 30000, null, false, "904a1892-6d65-4918-82a6-ba129017f21b", "")
            {
                _spantagdijitalgiftcard25Info = new RepoItemInfo(this, "SpanTagDijitalGiftCard25", "div[1]/div[1]/?/?/section/div[2]/div/div[1]/?/?/span[@innertext>'            Dijital Gift']", "span[@innertext>'            Dijital Gift']", 30000, null, "9567966b-4699-438a-9fe2-be9aec318fad");
                _spantagdijitalgiftcard50Info = new RepoItemInfo(this, "SpanTagDijitalGiftCard50", "div[1]/div[1]/?/?/section/div[2]/div/div[2]/?/?/span[@innertext>'            Dijital Gift']", "section/div[2]/div/div[2]/div[2]/span[@innertext>'            Dijital Gift']", 30000, null, "1da75574-2844-4554-ab11-39a9bcdb715d");
                _headeruyegirisiInfo = new RepoItemInfo(this, "HeaderUyeGirisi", "header/div[2]/div[1]/div[2]/div/div[3]/ul/?/?/ul//span[@innertext='Üye Girişi']", "span[@innertext='Üye Girişi']", 30000, null, "ba005f47-8d94-47e5-aaa9-53d5f3d09823");
                _testtestInfo = new RepoItemInfo(this, "TestTest", "header/div[2]/div[1]/div[2]/div/div[3]/ul/li[1]/?/?/span[@innertext='test test']", "span[@innertext='test test']", 30000, null, "6d539be1-9fd5-4f68-9b6a-d82b08fc7bd1");
                _btnfavpageInfo = new RepoItemInfo(this, "BtnFavPage", "div[1]/header/div[2]/div[1]/div[2]/div/div[3]/ul/li[3]", "header/div[2]/div[1]/div[2]/div/div[3]/ul/li[3]", 30000, null, "8aaf460a-c6fd-4e36-8784-1cc88eca260d");
                _personalfavorite1Info = new RepoItemInfo(this, "PersonalFavorite1", "header/div[2]/div[1]/div[2]/div/div[3]/ul/li[3]", "?/header/div[2]/div[1]/div[2]/div/div[3]/ul/li[3]", 30000, null, "86ee1ac8-a85e-44d4-9d6d-e22d745b80ea");
                _btnuserInfo = new RepoItemInfo(this, "BtnUser", "header/div[2]/div[1]/div[2]/div/div[3]/ul/li[1]/a[@href>'https://www.boyner.com.tr']", "?/header/div[2]/div[1]/div[2]/div/div[3]/ul/li[1]/a[@href>'https://www.boyner.com.tr']", 30000, null, "d0fb77d6-8d72-42bb-9322-7b725238ba39");
                _btnfavoritesInfo = new RepoItemInfo(this, "BtnFavorites", "header/div[2]/div[1]/div[2]/div/div[3]/ul/li[1]/?/?/ul/?/?/a[@innertext='Favorilerim']", "a[@innertext='Favorilerim']", 30000, null, "2e3a46d3-b184-4780-8104-7f3e870143f9");
                _btnbasketInfo = new RepoItemInfo(this, "BtnBasket", "header/div[2]/div[1]/div[2]/div/div[3]/ul/li[5]/?/?/span[@innertext='Sepetim']", "span[@innertext='Sepetim']", 30000, null, "b99a2d87-288a-4fc5-9ad9-cb35b61dcd02");
                _btnsignoutInfo = new RepoItemInfo(this, "BtnSignOut", "header/div[2]/div[1]/div[2]/div/div[3]/ul/li[1]/?/?/ul/?/?/a[@innertext='Çıkış']", "a[@innertext='Çıkış']", 30000, null, "50188c76-8884-4ae0-a0d3-0fb32716911b");
                _yardımInfo = new RepoItemInfo(this, "Yardım", "header/div[1]/div/div/div[2]/ul/?/?/a[@innertext='Yardım']", "a[@innertext='Yardım']", 30000, null, "91b8ee5b-1ed0-4822-8d8d-70689749ed0a");
                _spantag300tlplusalışverişlerinizdeueInfo = new RepoItemInfo(this, "SpanTag300TLPlusAlışverişlerinizdeUE", "header/div[1]//ul/?/?/div/li[2]/?/?/span[@innertext>'300 TL + alışverişlerinizde']", "span[@innertext>'300 TL + alışverişlerinizde']", 30000, null, "3c652a3c-cdfb-4769-8a3d-576af30647b2");
                _yardimInfo = new RepoItemInfo(this, "YARDIM", ".//section/?/?/h1[@innertext='YARDIM']", "h1[@innertext='YARDIM']", 30000, null, "c6f3eda0-8dd7-45cf-9812-79dce0d263ec");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("904a1892-6d65-4918-82a6-ba129017f21b")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("904a1892-6d65-4918-82a6-ba129017f21b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SpanTagDijitalGiftCard25 item.
            /// </summary>
            [RepositoryItem("9567966b-4699-438a-9fe2-be9aec318fad")]
            public virtual Ranorex.SpanTag SpanTagDijitalGiftCard25
            {
                get
                {
                    return _spantagdijitalgiftcard25Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagDijitalGiftCard25 item info.
            /// </summary>
            [RepositoryItemInfo("9567966b-4699-438a-9fe2-be9aec318fad")]
            public virtual RepoItemInfo SpanTagDijitalGiftCard25Info
            {
                get
                {
                    return _spantagdijitalgiftcard25Info;
                }
            }

            /// <summary>
            /// The SpanTagDijitalGiftCard50 item.
            /// </summary>
            [RepositoryItem("1da75574-2844-4554-ab11-39a9bcdb715d")]
            public virtual Ranorex.SpanTag SpanTagDijitalGiftCard50
            {
                get
                {
                    return _spantagdijitalgiftcard50Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagDijitalGiftCard50 item info.
            /// </summary>
            [RepositoryItemInfo("1da75574-2844-4554-ab11-39a9bcdb715d")]
            public virtual RepoItemInfo SpanTagDijitalGiftCard50Info
            {
                get
                {
                    return _spantagdijitalgiftcard50Info;
                }
            }

            /// <summary>
            /// The HeaderUyeGirisi item.
            /// </summary>
            [RepositoryItem("ba005f47-8d94-47e5-aaa9-53d5f3d09823")]
            public virtual Ranorex.SpanTag HeaderUyeGirisi
            {
                get
                {
                    return _headeruyegirisiInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The HeaderUyeGirisi item info.
            /// </summary>
            [RepositoryItemInfo("ba005f47-8d94-47e5-aaa9-53d5f3d09823")]
            public virtual RepoItemInfo HeaderUyeGirisiInfo
            {
                get
                {
                    return _headeruyegirisiInfo;
                }
            }

            /// <summary>
            /// The TestTest item.
            /// </summary>
            [RepositoryItem("6d539be1-9fd5-4f68-9b6a-d82b08fc7bd1")]
            public virtual Ranorex.SpanTag TestTest
            {
                get
                {
                    return _testtestInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TestTest item info.
            /// </summary>
            [RepositoryItemInfo("6d539be1-9fd5-4f68-9b6a-d82b08fc7bd1")]
            public virtual RepoItemInfo TestTestInfo
            {
                get
                {
                    return _testtestInfo;
                }
            }

            /// <summary>
            /// The BtnFavPage item.
            /// </summary>
            [RepositoryItem("8aaf460a-c6fd-4e36-8784-1cc88eca260d")]
            public virtual Ranorex.LiTag BtnFavPage
            {
                get
                {
                    return _btnfavpageInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The BtnFavPage item info.
            /// </summary>
            [RepositoryItemInfo("8aaf460a-c6fd-4e36-8784-1cc88eca260d")]
            public virtual RepoItemInfo BtnFavPageInfo
            {
                get
                {
                    return _btnfavpageInfo;
                }
            }

            /// <summary>
            /// The PersonalFavorite1 item.
            /// </summary>
            [RepositoryItem("86ee1ac8-a85e-44d4-9d6d-e22d745b80ea")]
            public virtual Ranorex.LiTag PersonalFavorite1
            {
                get
                {
                    return _personalfavorite1Info.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The PersonalFavorite1 item info.
            /// </summary>
            [RepositoryItemInfo("86ee1ac8-a85e-44d4-9d6d-e22d745b80ea")]
            public virtual RepoItemInfo PersonalFavorite1Info
            {
                get
                {
                    return _personalfavorite1Info;
                }
            }

            /// <summary>
            /// The BtnUser item.
            /// </summary>
            [RepositoryItem("d0fb77d6-8d72-42bb-9322-7b725238ba39")]
            public virtual Ranorex.ATag BtnUser
            {
                get
                {
                    return _btnuserInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BtnUser item info.
            /// </summary>
            [RepositoryItemInfo("d0fb77d6-8d72-42bb-9322-7b725238ba39")]
            public virtual RepoItemInfo BtnUserInfo
            {
                get
                {
                    return _btnuserInfo;
                }
            }

            /// <summary>
            /// The BtnFavorites item.
            /// </summary>
            [RepositoryItem("2e3a46d3-b184-4780-8104-7f3e870143f9")]
            public virtual Ranorex.ATag BtnFavorites
            {
                get
                {
                    return _btnfavoritesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BtnFavorites item info.
            /// </summary>
            [RepositoryItemInfo("2e3a46d3-b184-4780-8104-7f3e870143f9")]
            public virtual RepoItemInfo BtnFavoritesInfo
            {
                get
                {
                    return _btnfavoritesInfo;
                }
            }

            /// <summary>
            /// The BtnBasket item.
            /// </summary>
            [RepositoryItem("b99a2d87-288a-4fc5-9ad9-cb35b61dcd02")]
            public virtual Ranorex.SpanTag BtnBasket
            {
                get
                {
                    return _btnbasketInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The BtnBasket item info.
            /// </summary>
            [RepositoryItemInfo("b99a2d87-288a-4fc5-9ad9-cb35b61dcd02")]
            public virtual RepoItemInfo BtnBasketInfo
            {
                get
                {
                    return _btnbasketInfo;
                }
            }

            /// <summary>
            /// The BtnSignOut item.
            /// </summary>
            [RepositoryItem("50188c76-8884-4ae0-a0d3-0fb32716911b")]
            public virtual Ranorex.ATag BtnSignOut
            {
                get
                {
                    return _btnsignoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BtnSignOut item info.
            /// </summary>
            [RepositoryItemInfo("50188c76-8884-4ae0-a0d3-0fb32716911b")]
            public virtual RepoItemInfo BtnSignOutInfo
            {
                get
                {
                    return _btnsignoutInfo;
                }
            }

            /// <summary>
            /// The Yardım item.
            /// </summary>
            [RepositoryItem("91b8ee5b-1ed0-4822-8d8d-70689749ed0a")]
            public virtual Ranorex.ATag Yardım
            {
                get
                {
                    return _yardımInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Yardım item info.
            /// </summary>
            [RepositoryItemInfo("91b8ee5b-1ed0-4822-8d8d-70689749ed0a")]
            public virtual RepoItemInfo YardımInfo
            {
                get
                {
                    return _yardımInfo;
                }
            }

            /// <summary>
            /// The SpanTag300TLPlusAlışverişlerinizdeUE item.
            /// </summary>
            [RepositoryItem("3c652a3c-cdfb-4769-8a3d-576af30647b2")]
            public virtual Ranorex.SpanTag SpanTag300TLPlusAlışverişlerinizdeUE
            {
                get
                {
                    return _spantag300tlplusalışverişlerinizdeueInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTag300TLPlusAlışverişlerinizdeUE item info.
            /// </summary>
            [RepositoryItemInfo("3c652a3c-cdfb-4769-8a3d-576af30647b2")]
            public virtual RepoItemInfo SpanTag300TLPlusAlışverişlerinizdeUEInfo
            {
                get
                {
                    return _spantag300tlplusalışverişlerinizdeueInfo;
                }
            }

            /// <summary>
            /// The YARDIM item.
            /// </summary>
            [RepositoryItem("c6f3eda0-8dd7-45cf-9812-79dce0d263ec")]
            public virtual Ranorex.H1Tag YARDIM
            {
                get
                {
                    return _yardimInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The YARDIM item info.
            /// </summary>
            [RepositoryItemInfo("c6f3eda0-8dd7-45cf-9812-79dce0d263ec")]
            public virtual RepoItemInfo YARDIMInfo
            {
                get
                {
                    return _yardimInfo;
                }
            }
        }

        /// <summary>
        /// The DivTagRowFolder folder.
        /// </summary>
        [RepositoryFolder("946e5a7a-6111-482a-b10d-17d676db1f4a")]
        public partial class DivTagRowFolder : RepoGenBaseFolder
        {
            RepoItemInfo _sepetionaylaInfo;
            RepoItemInfo _h3tagteslimInfo;
            RepoItemInfo _h3tagguevenInfo;
            RepoItemInfo _boynercomtryeueyeolduğunuzdayenilikInfo;
            RepoItemInfo _nedenueyeolmalıyımInfo;
            RepoItemInfo _ueyeolmadanalışverişyapabilirmiyimInfo;
            RepoItemInfo _ueyeolmadandaboynercomtruezerindenInfo;
            RepoItemInfo _şifremiunuttumneyapmalıyımInfo;

            /// <summary>
            /// Creates a new DivTagRow  folder.
            /// </summary>
            public DivTagRowFolder(RepoGenBaseFolder parentFolder) :
                    base("DivTagRow", "body/div[1]/div[1]", parentFolder, 30000, null, false, "946e5a7a-6111-482a-b10d-17d676db1f4a", "")
            {
                _sepetionaylaInfo = new RepoItemInfo(this, "SepetiOnayla", ".//button[@innertext='Sepeti Onayla']", "", 30000, null, "a7c892ee-f64a-494b-92e3-59b8c52f106c");
                _h3tagteslimInfo = new RepoItemInfo(this, "H3TagTeslim", "div/div/div[1]/ul//h3[@innertext>'']", "", 30000, null, "960f41b8-32ea-4a55-8775-1564182a0806");
                _h3tagguevenInfo = new RepoItemInfo(this, "H3TagGueven", "div/div/div[1]/ul/li[2]/a[@href>'https://www.boyner.com.tr']/h3[@innertext>'']", "a[@href>'https://www.boyner.com.tr']/h3[@innertext>'']", 30000, null, "1a05f75b-cb5f-4ab9-b56b-2a8252b9ab9a");
                _boynercomtryeueyeolduğunuzdayenilikInfo = new RepoItemInfo(this, "BoynerComTryeUeyeOlduğunuzdaYenilik", ".//section/div[2]/div/div[1]/div[2]//p[@innertext>'Boyner.com.tr’ye üye olduğunuzda']", "", 30000, null, "a1e2552b-f329-46c2-abfb-5f9c92c90bdd");
                _nedenueyeolmalıyımInfo = new RepoItemInfo(this, "NedenUeyeOlmalıyım", ".//section//div[@innertext='Neden üye olmalıyım?']", "", 30000, null, "32095685-ac84-4b10-a519-f8920a160da8");
                _ueyeolmadanalışverişyapabilirmiyimInfo = new RepoItemInfo(this, "UEyeOlmadanAlışverişYapabilirMiyim", ".//section//div[@innertext>'Üye olmadan alışveriş yapabilir']", "", 30000, null, "7f1e581d-05d5-40ee-8776-101ce07f432b");
                _ueyeolmadandaboynercomtruezerindenInfo = new RepoItemInfo(this, "UEyeOlmadanDaBoynerComTrUezerinden", ".//section/div[2]/div/div[1]/div[4]//p[@innertext>'Üye olmadan da boyner.com.tr']", "", 30000, null, "a1cf9816-c472-4d38-a321-2824ef80a42b");
                _şifremiunuttumneyapmalıyımInfo = new RepoItemInfo(this, "ŞifremiUnuttumNeYapmalıyım", ".//section//div[@innertext>'Şifremi unuttum, ne yapma']", "", 30000, null, "d2febc53-c92e-4eed-a50c-3b30a8d8f28c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("946e5a7a-6111-482a-b10d-17d676db1f4a")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("946e5a7a-6111-482a-b10d-17d676db1f4a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SepetiOnayla item.
            /// </summary>
            [RepositoryItem("a7c892ee-f64a-494b-92e3-59b8c52f106c")]
            public virtual Ranorex.ButtonTag SepetiOnayla
            {
                get
                {
                    return _sepetionaylaInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SepetiOnayla item info.
            /// </summary>
            [RepositoryItemInfo("a7c892ee-f64a-494b-92e3-59b8c52f106c")]
            public virtual RepoItemInfo SepetiOnaylaInfo
            {
                get
                {
                    return _sepetionaylaInfo;
                }
            }

            /// <summary>
            /// The H3TagTeslim item.
            /// </summary>
            [RepositoryItem("960f41b8-32ea-4a55-8775-1564182a0806")]
            public virtual Ranorex.H3Tag H3TagTeslim
            {
                get
                {
                    return _h3tagteslimInfo.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The H3TagTeslim item info.
            /// </summary>
            [RepositoryItemInfo("960f41b8-32ea-4a55-8775-1564182a0806")]
            public virtual RepoItemInfo H3TagTeslimInfo
            {
                get
                {
                    return _h3tagteslimInfo;
                }
            }

            /// <summary>
            /// The H3TagGueven item.
            /// </summary>
            [RepositoryItem("1a05f75b-cb5f-4ab9-b56b-2a8252b9ab9a")]
            public virtual Ranorex.H3Tag H3TagGueven
            {
                get
                {
                    return _h3tagguevenInfo.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The H3TagGueven item info.
            /// </summary>
            [RepositoryItemInfo("1a05f75b-cb5f-4ab9-b56b-2a8252b9ab9a")]
            public virtual RepoItemInfo H3TagGuevenInfo
            {
                get
                {
                    return _h3tagguevenInfo;
                }
            }

            /// <summary>
            /// The BoynerComTryeUeyeOlduğunuzdaYenilik item.
            /// </summary>
            [RepositoryItem("a1e2552b-f329-46c2-abfb-5f9c92c90bdd")]
            public virtual Ranorex.PTag BoynerComTryeUeyeOlduğunuzdaYenilik
            {
                get
                {
                    return _boynercomtryeueyeolduğunuzdayenilikInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The BoynerComTryeUeyeOlduğunuzdaYenilik item info.
            /// </summary>
            [RepositoryItemInfo("a1e2552b-f329-46c2-abfb-5f9c92c90bdd")]
            public virtual RepoItemInfo BoynerComTryeUeyeOlduğunuzdaYenilikInfo
            {
                get
                {
                    return _boynercomtryeueyeolduğunuzdayenilikInfo;
                }
            }

            /// <summary>
            /// The NedenUeyeOlmalıyım item.
            /// </summary>
            [RepositoryItem("32095685-ac84-4b10-a519-f8920a160da8")]
            public virtual Ranorex.DivTag NedenUeyeOlmalıyım
            {
                get
                {
                    return _nedenueyeolmalıyımInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NedenUeyeOlmalıyım item info.
            /// </summary>
            [RepositoryItemInfo("32095685-ac84-4b10-a519-f8920a160da8")]
            public virtual RepoItemInfo NedenUeyeOlmalıyımInfo
            {
                get
                {
                    return _nedenueyeolmalıyımInfo;
                }
            }

            /// <summary>
            /// The UEyeOlmadanAlışverişYapabilirMiyim item.
            /// </summary>
            [RepositoryItem("7f1e581d-05d5-40ee-8776-101ce07f432b")]
            public virtual Ranorex.DivTag UEyeOlmadanAlışverişYapabilirMiyim
            {
                get
                {
                    return _ueyeolmadanalışverişyapabilirmiyimInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOlmadanAlışverişYapabilirMiyim item info.
            /// </summary>
            [RepositoryItemInfo("7f1e581d-05d5-40ee-8776-101ce07f432b")]
            public virtual RepoItemInfo UEyeOlmadanAlışverişYapabilirMiyimInfo
            {
                get
                {
                    return _ueyeolmadanalışverişyapabilirmiyimInfo;
                }
            }

            /// <summary>
            /// The UEyeOlmadanDaBoynerComTrUezerinden item.
            /// </summary>
            [RepositoryItem("a1cf9816-c472-4d38-a321-2824ef80a42b")]
            public virtual Ranorex.PTag UEyeOlmadanDaBoynerComTrUezerinden
            {
                get
                {
                    return _ueyeolmadandaboynercomtruezerindenInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOlmadanDaBoynerComTrUezerinden item info.
            /// </summary>
            [RepositoryItemInfo("a1cf9816-c472-4d38-a321-2824ef80a42b")]
            public virtual RepoItemInfo UEyeOlmadanDaBoynerComTrUezerindenInfo
            {
                get
                {
                    return _ueyeolmadandaboynercomtruezerindenInfo;
                }
            }

            /// <summary>
            /// The ŞifremiUnuttumNeYapmalıyım item.
            /// </summary>
            [RepositoryItem("d2febc53-c92e-4eed-a50c-3b30a8d8f28c")]
            public virtual Ranorex.DivTag ŞifremiUnuttumNeYapmalıyım
            {
                get
                {
                    return _şifremiunuttumneyapmalıyımInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ŞifremiUnuttumNeYapmalıyım item info.
            /// </summary>
            [RepositoryItemInfo("d2febc53-c92e-4eed-a50c-3b30a8d8f28c")]
            public virtual RepoItemInfo ŞifremiUnuttumNeYapmalıyımInfo
            {
                get
                {
                    return _şifremiunuttumneyapmalıyımInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
