///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test_Case.Recordings.CaseHash8
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ReportAskedQuestion recording.
    /// </summary>
    [TestModule("8e3133df-8334-4fcb-80e6-7d3db74c9805", ModuleType.Recording, 1)]
    public partial class ReportAskedQuestion : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Test_Case.Test_CaseRepository repository.
        /// </summary>
        public static global::Test_Case.Test_CaseRepository repo = global::Test_Case.Test_CaseRepository.Instance;

        static ReportAskedQuestion instance = new ReportAskedQuestion();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ReportAskedQuestion()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ReportAskedQuestion Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.PageWrapper.Yardım' at 30;16.", repo.TestCaseStudy.PageWrapper.YardımInfo, new RecordItemIndex(0));
            repo.TestCaseStudy.PageWrapper.Yardım.Click("30;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.DivTagRow.NedenUeyeOlmalıyım' at 125;22.", repo.TestCaseStudy.DivTagRow.NedenUeyeOlmalıyımInfo, new RecordItemIndex(1));
            repo.TestCaseStudy.DivTagRow.NedenUeyeOlmalıyım.Click("125;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "Boyner.com.tr’ye üye olduğunuzda yenilikler, fırsatlar ve kampanyalardan öncelikli olarak haberdar olabilir, size özel alışveriş olanaklarından faydalanabilir, siparişlerinizi \"Hesabım\" sayfasından kolayca takip edebilirsiniz.", new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.DivTagRow.UEyeOlmadanAlışverişYapabilirMiyim' at 236;15.", repo.TestCaseStudy.DivTagRow.UEyeOlmadanAlışverişYapabilirMiyimInfo, new RecordItemIndex(3));
            repo.TestCaseStudy.DivTagRow.UEyeOlmadanAlışverişYapabilirMiyim.Click("236;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "Üye olmadan da boyner.com.tr üzerinden alışveriş yapabilirsiniz. Beğendiğiniz ürünleri sepetinize ekledikten sonra \"Üye olmadan satın al\" alanını işaretleyip e-mail adresinizi ekleyerek alışverişinizi tamamlayabilirsiniz. Üye olmadan verdiğiniz siparişlerin takibi için; sayfamızın en altında bulunan \"Yardım\" başlığının altında \"Sipariş takibi\" sekmesine tıklayarak e-mail adresiniz ve sipariş numaranızı girip ürünlerinizin güncel durumuna ulaşabilirsiniz.", new RecordItemIndex(4));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.RegisterForm.UEyelikBilgilerimiVeIletişimIzinleri' at 221;18.", repo.TestCaseStudy.RegisterForm.UEyelikBilgilerimiVeIletişimIzinleriInfo, new RecordItemIndex(5));
            repo.TestCaseStudy.RegisterForm.UEyelikBilgilerimiVeIletişimIzinleri.Click("221;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "Üyeliğinize giriş yaptıktan sonra sağ üst kısımda yer alan isim bilginize tıklarsanız \"Hesabım\" alanı açılacaktır. Bu sayfada yer alan İsim, Soy isim, Doğum tarihi ve Cep telefon numarası gibi alanlarda dilediğiniz bilgi değişikliğini yapabilirsiniz. E-mail adresi için her üyelik için tekil olduğundan E-mail adres değişikliği yapılamamaktadır.", new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.DivTagRow.ŞifremiUnuttumNeYapmalıyım' at 195;23.", repo.TestCaseStudy.DivTagRow.ŞifremiUnuttumNeYapmalıyımInfo, new RecordItemIndex(7));
            repo.TestCaseStudy.DivTagRow.ŞifremiUnuttumNeYapmalıyım.Click("195;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "Boyner.com.tr'ye üye olurken kullandığınız şifrenizi unuttuysanız \"Üye Girişi\" bölümünden \"Şifremi Unuttum\" alanına tıkladığınızda üyelik e-mail adresinizi girebileceğiniz alan açılacaktır. E-mail adresini girip \"Gönder\" butonuna tıkladığınızda şifre linki e-mail adresinize gönderilecektir. Gelen linke tıkladığınızda açılan sayfada yeni şifrenizi belirleyerek hesabınıza giriş yapabilirsiniz.", new RecordItemIndex(8));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='YARDIM') on item 'TestCaseStudy.PageWrapper.YARDIM'.", repo.TestCaseStudy.PageWrapper.YARDIMInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.TestCaseStudy.PageWrapper.YARDIMInfo, "InnerText", "YARDIM");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
