///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test_Case.Recordings.CaseHash6
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyAfterBasket recording.
    /// </summary>
    [TestModule("38043c12-c14d-4660-a447-c7ffdae008d3", ModuleType.Recording, 1)]
    public partial class VerifyAfterBasket : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Test_Case.Test_CaseRepository repository.
        /// </summary>
        public static global::Test_Case.Test_CaseRepository repo = global::Test_Case.Test_CaseRepository.Instance;

        static VerifyAfterBasket instance = new VerifyAfterBasket();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyAfterBasket()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyAfterBasket Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.DivTagRow.SepetiOnayla' at 159;37.", repo.TestCaseStudy.DivTagRow.SepetiOnaylaInfo, new RecordItemIndex(0));
            repo.TestCaseStudy.DivTagRow.SepetiOnayla.Click("159;37");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='o-step__item -active') on item 'TestCaseStudy.OStepItem'.", repo.TestCaseStudy.OStepItemInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.TestCaseStudy.OStepItemInfo, "Class", "o-step__item -active");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='o-step__item') on item 'TestCaseStudy.OStepItem1'.", repo.TestCaseStudy.OStepItem1Info, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.TestCaseStudy.OStepItem1Info, "Class", "o-step__item");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='delivery') on item 'TestCaseStudy.Delivery'.", repo.TestCaseStudy.DeliveryInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.TestCaseStudy.DeliveryInfo, "Id", "delivery");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
