///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test_Case.Recordings.CaseHash3
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BlankSurname recording.
    /// </summary>
    [TestModule("022ea851-502e-4648-9968-92a0c37efad0", ModuleType.Recording, 1)]
    public partial class BlankSurname : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Test_Case.Test_CaseRepository repository.
        /// </summary>
        public static global::Test_Case.Test_CaseRepository repo = global::Test_Case.Test_CaseRepository.Instance;

        static BlankSurname instance = new BlankSurname();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BlankSurname()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BlankSurname Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.HeaderUyeOl' at 12;13.", repo.TestCaseStudy.HeaderUyeOlInfo, new RecordItemIndex(0));
            repo.TestCaseStudy.HeaderUyeOl.Click("12;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.FieldName' at 65;28.", repo.TestCaseStudy.FieldNameInfo, new RecordItemIndex(1));
            repo.TestCaseStudy.FieldName.Click("65;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'TestCaseStudy.FieldName'.", repo.TestCaseStudy.FieldNameInfo, new RecordItemIndex(2));
            repo.TestCaseStudy.FieldName.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.FieldSurname' at 7;40.", repo.TestCaseStudy.FieldSurnameInfo, new RecordItemIndex(3));
            repo.TestCaseStudy.FieldSurname.Click("7;40");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '    ' with focus on 'TestCaseStudy.FieldSurname'.", repo.TestCaseStudy.FieldSurnameInfo, new RecordItemIndex(4));
            repo.TestCaseStudy.FieldSurname.PressKeys("    ");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.FieldEmail' at 71;31.", repo.TestCaseStudy.FieldEmailInfo, new RecordItemIndex(5));
            repo.TestCaseStudy.FieldEmail.Click("71;31");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'seleniumtester102@gmail.com' with focus on 'TestCaseStudy.FieldEmail'.", repo.TestCaseStudy.FieldEmailInfo, new RecordItemIndex(6));
            repo.TestCaseStudy.FieldEmail.PressKeys("seleniumtester102@gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.FieldPassword' at 60;51.", repo.TestCaseStudy.FieldPasswordInfo, new RecordItemIndex(7));
            repo.TestCaseStudy.FieldPassword.Click("60;51");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Test102!' with focus on 'TestCaseStudy.FieldPassword'.", repo.TestCaseStudy.FieldPasswordInfo, new RecordItemIndex(8));
            repo.TestCaseStudy.FieldPassword.PressKeys("Test102!");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.FieldPasswordConfirmed' at 37;29.", repo.TestCaseStudy.FieldPasswordConfirmedInfo, new RecordItemIndex(9));
            repo.TestCaseStudy.FieldPasswordConfirmed.Click("37;29");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Test102!' with focus on 'TestCaseStudy.FieldPasswordConfirmed'.", repo.TestCaseStudy.FieldPasswordConfirmedInfo, new RecordItemIndex(10));
            repo.TestCaseStudy.FieldPasswordConfirmed.PressKeys("Test102!");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.FieldPhone' at 82;49.", repo.TestCaseStudy.FieldPhoneInfo, new RecordItemIndex(11));
            repo.TestCaseStudy.FieldPhone.Click("82;49");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '5303303030' with focus on 'TestCaseStudy.FieldPhone'.", repo.TestCaseStudy.FieldPhoneInfo, new RecordItemIndex(12));
            repo.TestCaseStudy.FieldPhone.PressKeys("5303303030");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.RegisterForm.SelectGender' at 127;36.", repo.TestCaseStudy.RegisterForm.SelectGenderInfo, new RecordItemIndex(13));
            repo.TestCaseStudy.RegisterForm.SelectGender.Click("127;36");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Return}' with focus on 'TestCaseStudy.RegisterForm.SelectGender'.", repo.TestCaseStudy.RegisterForm.SelectGenderInfo, new RecordItemIndex(14));
            repo.TestCaseStudy.RegisterForm.SelectGender.PressKeys("{Down}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.RegisterForm.SelectDay' at 56;26.", repo.TestCaseStudy.RegisterForm.SelectDayInfo, new RecordItemIndex(15));
            repo.TestCaseStudy.RegisterForm.SelectDay.Click("56;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Return}' with focus on 'TestCaseStudy.RegisterForm.SelectDay'.", repo.TestCaseStudy.RegisterForm.SelectDayInfo, new RecordItemIndex(16));
            repo.TestCaseStudy.RegisterForm.SelectDay.PressKeys("{Down}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.RegisterForm.SelectMonth' at 39;52.", repo.TestCaseStudy.RegisterForm.SelectMonthInfo, new RecordItemIndex(17));
            repo.TestCaseStudy.RegisterForm.SelectMonth.Click("39;52");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Return}' with focus on 'TestCaseStudy.RegisterForm.SelectMonth'.", repo.TestCaseStudy.RegisterForm.SelectMonthInfo, new RecordItemIndex(18));
            repo.TestCaseStudy.RegisterForm.SelectMonth.PressKeys("{Down}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.RegisterForm.SelectYear' at 24;41.", repo.TestCaseStudy.RegisterForm.SelectYearInfo, new RecordItemIndex(19));
            repo.TestCaseStudy.RegisterForm.SelectYear.Click("24;41");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Return}' with focus on 'TestCaseStudy.RegisterForm.SelectYear'.", repo.TestCaseStudy.RegisterForm.SelectYearInfo, new RecordItemIndex(20));
            repo.TestCaseStudy.RegisterForm.SelectYear.PressKeys("{Down}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.RegisterForm.CustomCheckboxLabel' at 26;12.", repo.TestCaseStudy.RegisterForm.CustomCheckboxLabelInfo, new RecordItemIndex(21));
            repo.TestCaseStudy.RegisterForm.CustomCheckboxLabel.Click("26;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.RegisterForm.CustomCheckboxLabel1' at 22;10.", repo.TestCaseStudy.RegisterForm.CustomCheckboxLabel1Info, new RecordItemIndex(22));
            repo.TestCaseStudy.RegisterForm.CustomCheckboxLabel1.Click("22;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestCaseStudy.RegisterForm.BtnSubmit' at 167;19.", repo.TestCaseStudy.RegisterForm.BtnSubmitInfo, new RecordItemIndex(23));
            repo.TestCaseStudy.RegisterForm.BtnSubmit.Click("167;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Bu alan boş bırakılamaz!') on item 'TestCaseStudy.ErrorForSurname'.", repo.TestCaseStudy.ErrorForSurnameInfo, new RecordItemIndex(24));
            Validate.AttributeEqual(repo.TestCaseStudy.ErrorForSurnameInfo, "InnerText", "Bu alan boş bırakılamaz!");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
